### ISSUE TITLE
Installs files directly in `/usr/local`

### ISSUE THREAD

**Issue by ulsa** [awslabs/aws-encryption-sdk-cli#122]
`IOError: [Errno 13] Permission denied: '/usr/local/CHANGELOG.rst'`

It seems files like `CHANGELOG.rst` are being installed directly in `/usr/local/`. That can't be right. I don't have write permission to that specific folder, which is the reason I noticed it.

MacOS 10.12.

```
$ brew --version
Homebrew 1.3.7-30-gdefd38a
Homebrew/homebrew-core (git revision 989e7; last commit 2017-11-19)

$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

$ pip install aws-encryption-sdk-cli
Collecting aws-encryption-sdk-cli
  Using cached aws_encryption_sdk_cli-1.1.1-py2.py3-none-any.whl
...
Installing collected packages: aws-encryption-sdk-cli
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/CHANGELOG.rst'
```

**Comment by lizroth** [comment]
Thank you for reaching out and reporting this issue. We're working on a fix and will make it available ASAP.

In the meantime, my apologies for the trouble. We'll post an update here as soon as one is available.

Thank you,
-Liz

**Comment by lizroth** [comment]
Hello again,

Version 1.1.2 has been pushed to PyPI. Please try your install again. I was able to reproduce your permissions error in my testing, and this patch should fix it for you.

If it does not, please do not hesitate to reopen this issue and let us know.

Thank you for reaching out!

-Liz

**Comment by ulsa** [comment]
It works. Thank you.
